
auth:
  id: omnia_auth
  secret: ${SECRET:-RANDOM_SECRET}

database:
      # the name of the JDBC driver, mysql in our case
      driverClass: com.mysql.jdbc.Driver
      # the username
      user: root
      # the password
      password: qburst
      # the JDBC URL; the database is called DropWizard
      url: jdbc:mysql://localhost:3306/sampleopenid?autoReconnect=true
      # any properties specific to your JDBC driver:
      properties:
        charSet: UTF-8
      # the maximum amount of time to wait on an empty pool before throwing an exception
      maxWaitForConnection: 1s
      # the SQL query to run when validating a connection's liveness
      validationQuery: "/* MyService Health Check */ SELECT 1"
      # the timeout before a connection validation queries fail
      validationQueryTimeout: 3s
      # the minimum number of connections to keep open
      minSize: 8
      # the maximum number of connections to keep open
      maxSize: 32
      # whether or not idle connections should be validated
      checkConnectionWhileIdle: true
      checkConnectionOnReturn: true
      checkConnectionOnBorrow: true
      # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
      evictionInterval: 10s
      # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
      minIdleTime: 1 minute


# Define the HTTP settings
server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 6060
  adminConnectors:
    - type: http
      port: 6061
  registerDefaultExceptionMappers: false

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: openid.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: openid-%d.log
      archivedFileCount: 5
      timeZone: UTC
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
